version: '2'
services:
    jhipstermarket-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipstermarket/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipstermarket
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
